# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVendaDePelis', '0002_auto_20170324_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='client',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.TextField(choices=[('Comedy', 'Comedy'), ('Action', 'Action'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Adventure', 'Adventure'), ('scienceFiction', 'scienceFiction'), ('Western', 'Western')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='price',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=4, verbose_name='Euro amount'),
        ),
    ]
