# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVendaDePelis', '0003_auto_20170416_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Action', 'Action'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Adventure', 'Adventure'), ('scienceFiction', 'scienceFiction'), ('Western', 'Western')], max_length=20, unique=True),
        ),
    ]
