# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVendaDePelis', '0004_auto_20170416_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='client',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
