# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iVendaDePelis', '0006_auto_20170416_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(related_name='actors', to='iVendaDePelis.Film'),
        ),
        migrations.AlterField(
            model_name='favouritelist',
            name='films',
            field=models.ManyToManyField(to='iVendaDePelis.Film'),
        ),
        migrations.AlterField(
            model_name='favouritelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='clients',
            field=models.ManyToManyField(related_name='films', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='iVendaDePelis.Film'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
