# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iVendaDePelis', '0009_auto_20170416_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritelist',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 21, 13, 24, 5, 351987, tzinfo=utc), verbose_name='Creation Date'),
        ),
    ]
