# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVendaDePelis', '0011_auto_20170421_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritelist',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
